# continue-in-finally (E0116)
*\'continue\' not supported inside \'finally\' clause* Emitted when the
continue keyword is found inside a finally clause, which is a
SyntaxError.
