# boolean-datetime (W1502)

*Using datetime.time in a boolean context.* Using datetime.time in a
boolean context can hide subtle bugs when the time they represent
matches midnight UTC. This behaviour was fixed in Python 3.5. See
<a href="http://bugs.python.org/issue13936" class="reference external">http://bugs.python.org/issue13936</a>
for reference. This message canâ€™t be emitted when using Python &gt;=
3.5.
